# This file was generated by GoReleaser. DO NOT EDIT.
cask "zordon" do
  version "0.22.3"

  on_macos do
    on_arm do
      sha256 "30fe06d7889037d40568b09febdad79781227a74c55220a5f1eb00a149ba80be"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e0f7398325ca295b99baba0743693d87f472460b901f17afe2658a125c61090c"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "768b8ae24aee471f8699d59d4cb373084c679fe27639371616995a7dc5c9619e"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2e1509d88709cc127a5e1433ad96235d6b841b8447c67e7557b3ee42d913ad47"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_linux_amd64.tar.gz"
    end
  end

  name "zordon"
  desc "Process supervisor for local agentic workflows: databases, brokers and services declared in an Alphasfile, run as host processes"
  homepage "https://zordon.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zordon"
  binary "alpha"
  binary "tommy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
