# This file was generated by GoReleaser. DO NOT EDIT.
cask "zordon" do
  version "0.20.0"

  on_macos do
    on_arm do
      sha256 "d398bd3e3aa35815d7d99345cc696f5e32b7517e4e19c895d18964a61b11bcad"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "45da4c8d7bc62328f6ccd7bb2f03df6481c49d83cf4501ed7a8b4bd6e80e0777"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0f9925fe6b631f72503953b9fd404e4bd38fa2636182ee95c5d618581d8f6050"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eac4097bd09c748468a3b3a91dabdecc6238a613df800e0f7f962f495b5c9f99"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_linux_amd64.tar.gz"
    end
  end

  name "zordon"
  desc "Process supervisor for local agentic workflows: databases, brokers and services declared in an Alphasfile, run as host processes"
  homepage "https://zordon.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zordon"
  binary "alpha"
  binary "tommy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
