# This file was generated by GoReleaser. DO NOT EDIT.
cask "zordon" do
  version "0.17.6"

  on_macos do
    on_intel do
      sha256 "b8a069018cb223a8d58b2a37c24203bb54684e4b570d9f8ffb54ce08ec0957d8"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "591f144778d1dde74d0c8a348d362fec5106885d79ab90df8853e1a7d0ba1be3"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2f2e976cf00d1773bc9ad85aeb21b4c013436635d9b3ab0f5231aa1d6529a94"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "898bdfc928e310fc8384eeef918d5b0fe93b489f91ed07154026be881787d5db"
      url "https://github.com/piotrkowalczuk/zordon/releases/download/v#{version}/zordon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zordon"
  desc "Process supervisor for local agentic workflows: databases, brokers and services declared in an Alphasfile, run as host processes"
  homepage "https://zordon.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zordon"
  binary "alpha"
  binary "tommy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
